### ISSUE TITLE
TypeError: unable to convert a QVariant of type 0 to a QMetaType of type 6

### ISSUE THREAD

**Issue by simgislab** [nextgis/qgis_digitizr#1]
При нажатии на setting получаю ошибку 

>2017-06-15T14:40:53 1 Traceback (most recent call last):
File "C:/Users/peter.potapov/.qgis2/python/plugins\digitizr\plugin.py", line 79, in showToolAddLineBufferButtonSettings
qgis_settings.value(settings.buffer_size_key, type=float)
TypeError: unable to convert a QVariant of type 0 to a QMetaType of type 6

**Comment by simgislab** [comment]
у меня не воспроизводится Win7 32bit, QGIS 17.6.0

**Comment by simgislab** [comment]
на Win10 QGIS 2.18.8 из OSGeo4W видел как воспроизводится
но на Win7 QGIS 2.18.9 из OSGeo4W не воспроизводится

**Comment by alisovenko** [comment]
Fixed.
