### ISSUE TITLE
При сохранении проекта и открывания вновь, плагин недоступен

### ISSUE THREAD

**Issue by simgislab** [nextgis/qgis_digitizr#2]
При сохранении проекта и открывания вновь, плагин недоступен (серые кнопки) даже после того как слой поставлен на editing

после переустановки плагина кнопка оживает

**Comment by simgislab** [comment]
проверил, у меня все ок, Win7 32bit, QGIS 17.6.0

**Comment by alisovenko** [comment]
Fixed.
