### ISSUE TITLE
Plugin menu location

### ISSUE THREAD

**Issue by sdnxgr** [nextgis/qgis_digitizr#4]
Thanks for developing this plugin. This isn't really a bug or issue so I apologize for the annoyance:
Installed digitizr on QGIS 2.18 but for the life of me, I can't find the plugin in any menu or toolbar when activated.
I'm sure it's in there somewhere, but a hint would be much appreciated.

**Comment by simgislab** [comment]
Hi,

no menu item for it yet, but try Plugins toolbar
