### ISSUE TITLE
Icon is greyed out

### ISSUE THREAD

**Issue by rodjur** [nextgis/qgis_digitizr#6]
Hi, after installing the plugin and creating a new vector line file the 'Add Line Buffer' icon stays greyed out.
Also after several deactivating and reactivating actions of the plugin in the Plugins manager, more icons appear on the toolbar.
I use Qgis 3.22.13

Thanks

**Comment by simgislab** [comment]
Steps to replicate:

1. Install plugin, turn it on
2. Create new temporary layer, linestring

Plugin's button is greyed out.

**Comment by simgislab** [comment]
try creating a polygon layer, not a line one

**Comment by ivanbarsukov** [comment]
Fixed in version 1.0.1
