### ISSUE TITLE
Неактивная кнопка модуля на тулбаре в QGIS

### ISSUE THREAD

**Issue by cybergeo82** [nextgis/qgis_digitizr#7]
После установки модуля и создания полигонального слоя, кнопка модуля остаётся серой – то есть недоступной для активации. Доступной для активации она становится после того, как начинаешь рисовать полигон – то есть после начала работы с сами слоем. Иными словами, чтобы получить возможность активировать модуль надо сначала начать рисовать ненужный полигон.

https://user-images.githubusercontent.com/101568545/222361881-db3b2d28-1b88-487a-a1da-4d147fc416f7.mp4

**Comment by simgislab** [comment]
если слой уже существует - то подтверждается
если слой создавать тут же - то все нормально , кнопка активируется

в целом там бардак в Qt-шных методах инициализации/удаления модуля

связано с https://github.com/nextgis/qgis_digitizr/issues/6

**Comment by simgislab** [comment]
Шаги для воспроизведения:

1. Чистый проект
2. Создать Новый временный слой, тип Полигон, ОК -> иконка модуля активирована [это правильно]
3. Меню: Слой - Режим редактирования -> иконка модуля дезактивирована [это правильно]
4. Меню: Слой - Режим редактирования -> иконка дезактивирована [это не правильно]

Это проблема, при переходе в режим редактирования подходящего слоя кнопка должна снова активироваться.

**Comment by ivanbarsukov** [comment]
Fixed in version 1.0.1
