### ISSUE TITLE
Incorrent load/unload of the plugin

### ISSUE THREAD

**Issue by simgislab** [nextgis/qgis_digitizr#8]
after several deactivating and reactivating actions of the plugin in the Plugins manager, more icons appear on the toolbar.

Steps to reproduce:

1. Start QGIS
2. Turn on the plugin (Plugins menu\Manage and install plugins) -> see the button appear
3. Turn off the plugin -> button doesn't disappear
4. Turn on the plugin -> see a copy of the button appear

See video: https://m-d.me/img/ss/20230418_151930.mp4

**Comment by ivanbarsukov** [comment]
Fixed by https://github.com/nextgis/qgis_digitizr/pull/10
